import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

import { Navbar } from '@/components/navbar'
import './globals.css'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={rubik.className}>
				<Navbar
					navItems={[
						{ label: 'Home', link: '/' },
						{ label: 'Tickets', link: '/tickets' }
					]}
				/>
				<div className="px-5">{children}</div>
			</body>
		</html>
	)
}
